server:
    port: 8089

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/fungimap?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      #password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#    dbcp2:
#      min-idle: 5
#      initial-size: 5
#      max-total: 5
#      max-wait-millis: 200
   devtools:
      restart:
          enabled: true  #设置开启热部署
   freemarker:
      cache: false    #页面不加载缓存，修改即时生效

   thymeleaf:
      cache: false

mybatis:
   mapper-locations: classpath:/mapper/*.xml

redis:
  spring:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379




