package com.guizhou.map.domain;

public class coordinatetoimgid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_longla.id
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_longla.longitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_longla.latitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_longla.genus1
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    private String genus1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_longla.id
     *
     * @return the value of id_longla.id
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_longla.id
     *
     * @param id the value for id_longla.id
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_longla.longitude
     *
     * @return the value of id_longla.longitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_longla.longitude
     *
     * @param longitude the value for id_longla.longitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_longla.latitude
     *
     * @return the value of id_longla.latitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_longla.latitude
     *
     * @param latitude the value for id_longla.latitude
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_longla.genus1
     *
     * @return the value of id_longla.genus1
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public String getGenus1() {
        return genus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_longla.genus1
     *
     * @param genus1 the value for id_longla.genus1
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    public void setGenus1(String genus1) {
        this.genus1 = genus1 == null ? null : genus1.trim();
    }
}