package com.guizhou.map.domain;

import java.io.Serializable;

public class fungus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.id
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.name
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.creater
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.createdDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String createddeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.owner
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ownerDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String ownerdeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.createdTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.modifier
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.modifiedTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.workflowInstanceId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String workflowinstanceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.sequenceNo
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String sequenceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.sequenceStatus
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String sequencestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ownerDeptQueryCode
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String ownerdeptquerycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.Date1567760819619
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String date1567760819619;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.Address1567760880211
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String address1567760880211;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.Address1567760918035
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String address1567760918035;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567760963892
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567760963892;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567760966363
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567760966363;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761085636
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761085636;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761116444
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761116444;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761191578
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761191578;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761353834
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761353834;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761364586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761364586;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761376219
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761376219;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761392962
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761392962;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761404563
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761404563;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761446290
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761446290;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761455594
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761455594;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761846314
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761846314;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761886218
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761886218;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761904178
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761904178;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567761983306
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567761983306;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762030586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762030586;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762120642
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762120642;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762172409
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762172409;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762180513
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762180513;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762191345
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762191345;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762656480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762656480;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762796954
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762796954;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567762822969
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567762822969;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567995553359
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567995553359;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1567995610591
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1567995610591;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1568085486500
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1568085486500;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1568085736789
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1568085736789;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1568259391751
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1568259391751;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728158252
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728158252;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728170780
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728170780;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728174540
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728174540;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728177604
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728177604;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728336907
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728336907;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728465060
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728465060;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569728948491
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569728948491;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569729016795
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569729016795;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569738095498
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569738095498;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569738368009
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569738368009;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569738587480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569738587480;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569738939775
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569738939775;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1569742452564
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1569742452564;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1570524392514
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1570524392514;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1571127984437
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1571127984437;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572406658886
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572406658886;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572406711365
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572406711365;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572406751109
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572406751109;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.RelevanceForm1572412237878
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String relevanceform1572412237878;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425570081
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425570081;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425616210
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425616210;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425629179
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425629179;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425638936
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425638936;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425645745
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425645745;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425675200
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425675200;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1572425697073
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1572425697073;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1578362642317
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1578362642317;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1578464014747
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1578464014747;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1578472359364
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1578472359364;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1583372194313
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1583372194313;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1584003163176
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1584003163176;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.ShortText1584003915711
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String shorttext1584003915711;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.city
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.country
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.value
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.id
     *
     * @return the value of igtgv_pjldc01dcb.id
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.id
     *
     * @param id the value for igtgv_pjldc01dcb.id
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.name
     *
     * @return the value of igtgv_pjldc01dcb.name
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.name
     *
     * @param name the value for igtgv_pjldc01dcb.name
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.creater
     *
     * @return the value of igtgv_pjldc01dcb.creater
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.creater
     *
     * @param creater the value for igtgv_pjldc01dcb.creater
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.createdDeptId
     *
     * @return the value of igtgv_pjldc01dcb.createdDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getCreateddeptid() {
        return createddeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.createdDeptId
     *
     * @param createddeptid the value for igtgv_pjldc01dcb.createdDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setCreateddeptid(String createddeptid) {
        this.createddeptid = createddeptid == null ? null : createddeptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.owner
     *
     * @return the value of igtgv_pjldc01dcb.owner
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.owner
     *
     * @param owner the value for igtgv_pjldc01dcb.owner
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ownerDeptId
     *
     * @return the value of igtgv_pjldc01dcb.ownerDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getOwnerdeptid() {
        return ownerdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ownerDeptId
     *
     * @param ownerdeptid the value for igtgv_pjldc01dcb.ownerDeptId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setOwnerdeptid(String ownerdeptid) {
        this.ownerdeptid = ownerdeptid == null ? null : ownerdeptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.createdTime
     *
     * @return the value of igtgv_pjldc01dcb.createdTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.createdTime
     *
     * @param createdtime the value for igtgv_pjldc01dcb.createdTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setCreatedtime(String createdtime) {
        this.createdtime = createdtime == null ? null : createdtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.modifier
     *
     * @return the value of igtgv_pjldc01dcb.modifier
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.modifier
     *
     * @param modifier the value for igtgv_pjldc01dcb.modifier
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.modifiedTime
     *
     * @return the value of igtgv_pjldc01dcb.modifiedTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.modifiedTime
     *
     * @param modifiedtime the value for igtgv_pjldc01dcb.modifiedTime
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setModifiedtime(String modifiedtime) {
        this.modifiedtime = modifiedtime == null ? null : modifiedtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.workflowInstanceId
     *
     * @return the value of igtgv_pjldc01dcb.workflowInstanceId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getWorkflowinstanceid() {
        return workflowinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.workflowInstanceId
     *
     * @param workflowinstanceid the value for igtgv_pjldc01dcb.workflowInstanceId
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setWorkflowinstanceid(String workflowinstanceid) {
        this.workflowinstanceid = workflowinstanceid == null ? null : workflowinstanceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.sequenceNo
     *
     * @return the value of igtgv_pjldc01dcb.sequenceNo
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.sequenceNo
     *
     * @param sequenceno the value for igtgv_pjldc01dcb.sequenceNo
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setSequenceno(String sequenceno) {
        this.sequenceno = sequenceno == null ? null : sequenceno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.sequenceStatus
     *
     * @return the value of igtgv_pjldc01dcb.sequenceStatus
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getSequencestatus() {
        return sequencestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.sequenceStatus
     *
     * @param sequencestatus the value for igtgv_pjldc01dcb.sequenceStatus
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setSequencestatus(String sequencestatus) {
        this.sequencestatus = sequencestatus == null ? null : sequencestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ownerDeptQueryCode
     *
     * @return the value of igtgv_pjldc01dcb.ownerDeptQueryCode
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getOwnerdeptquerycode() {
        return ownerdeptquerycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ownerDeptQueryCode
     *
     * @param ownerdeptquerycode the value for igtgv_pjldc01dcb.ownerDeptQueryCode
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setOwnerdeptquerycode(String ownerdeptquerycode) {
        this.ownerdeptquerycode = ownerdeptquerycode == null ? null : ownerdeptquerycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.Date1567760819619
     *
     * @return the value of igtgv_pjldc01dcb.Date1567760819619
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getDate1567760819619() {
        return date1567760819619;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.Date1567760819619
     *
     * @param date1567760819619 the value for igtgv_pjldc01dcb.Date1567760819619
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setDate1567760819619(String date1567760819619) {
        this.date1567760819619 = date1567760819619 == null ? null : date1567760819619.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.Address1567760880211
     *
     * @return the value of igtgv_pjldc01dcb.Address1567760880211
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getAddress1567760880211() {
        return address1567760880211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.Address1567760880211
     *
     * @param address1567760880211 the value for igtgv_pjldc01dcb.Address1567760880211
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setAddress1567760880211(String address1567760880211) {
        this.address1567760880211 = address1567760880211 == null ? null : address1567760880211.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.Address1567760918035
     *
     * @return the value of igtgv_pjldc01dcb.Address1567760918035
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getAddress1567760918035() {
        return address1567760918035;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.Address1567760918035
     *
     * @param address1567760918035 the value for igtgv_pjldc01dcb.Address1567760918035
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setAddress1567760918035(String address1567760918035) {
        this.address1567760918035 = address1567760918035 == null ? null : address1567760918035.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567760963892
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567760963892
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567760963892() {
        return shorttext1567760963892;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567760963892
     *
     * @param shorttext1567760963892 the value for igtgv_pjldc01dcb.ShortText1567760963892
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567760963892(String shorttext1567760963892) {
        this.shorttext1567760963892 = shorttext1567760963892 == null ? null : shorttext1567760963892.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567760966363
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567760966363
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567760966363() {
        return shorttext1567760966363;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567760966363
     *
     * @param shorttext1567760966363 the value for igtgv_pjldc01dcb.ShortText1567760966363
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567760966363(String shorttext1567760966363) {
        this.shorttext1567760966363 = shorttext1567760966363 == null ? null : shorttext1567760966363.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761085636
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761085636
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761085636() {
        return shorttext1567761085636;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761085636
     *
     * @param shorttext1567761085636 the value for igtgv_pjldc01dcb.ShortText1567761085636
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761085636(String shorttext1567761085636) {
        this.shorttext1567761085636 = shorttext1567761085636 == null ? null : shorttext1567761085636.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761116444
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761116444
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761116444() {
        return shorttext1567761116444;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761116444
     *
     * @param shorttext1567761116444 the value for igtgv_pjldc01dcb.ShortText1567761116444
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761116444(String shorttext1567761116444) {
        this.shorttext1567761116444 = shorttext1567761116444 == null ? null : shorttext1567761116444.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761191578
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761191578
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761191578() {
        return shorttext1567761191578;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761191578
     *
     * @param shorttext1567761191578 the value for igtgv_pjldc01dcb.ShortText1567761191578
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761191578(String shorttext1567761191578) {
        this.shorttext1567761191578 = shorttext1567761191578 == null ? null : shorttext1567761191578.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761353834
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761353834
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761353834() {
        return shorttext1567761353834;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761353834
     *
     * @param shorttext1567761353834 the value for igtgv_pjldc01dcb.ShortText1567761353834
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761353834(String shorttext1567761353834) {
        this.shorttext1567761353834 = shorttext1567761353834 == null ? null : shorttext1567761353834.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761364586
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761364586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761364586() {
        return shorttext1567761364586;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761364586
     *
     * @param shorttext1567761364586 the value for igtgv_pjldc01dcb.ShortText1567761364586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761364586(String shorttext1567761364586) {
        this.shorttext1567761364586 = shorttext1567761364586 == null ? null : shorttext1567761364586.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761376219
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761376219
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761376219() {
        return shorttext1567761376219;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761376219
     *
     * @param shorttext1567761376219 the value for igtgv_pjldc01dcb.ShortText1567761376219
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761376219(String shorttext1567761376219) {
        this.shorttext1567761376219 = shorttext1567761376219 == null ? null : shorttext1567761376219.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761392962
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761392962
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761392962() {
        return shorttext1567761392962;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761392962
     *
     * @param shorttext1567761392962 the value for igtgv_pjldc01dcb.ShortText1567761392962
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761392962(String shorttext1567761392962) {
        this.shorttext1567761392962 = shorttext1567761392962 == null ? null : shorttext1567761392962.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761404563
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761404563
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761404563() {
        return shorttext1567761404563;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761404563
     *
     * @param shorttext1567761404563 the value for igtgv_pjldc01dcb.ShortText1567761404563
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761404563(String shorttext1567761404563) {
        this.shorttext1567761404563 = shorttext1567761404563 == null ? null : shorttext1567761404563.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761446290
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761446290
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761446290() {
        return shorttext1567761446290;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761446290
     *
     * @param shorttext1567761446290 the value for igtgv_pjldc01dcb.ShortText1567761446290
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761446290(String shorttext1567761446290) {
        this.shorttext1567761446290 = shorttext1567761446290 == null ? null : shorttext1567761446290.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761455594
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761455594
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761455594() {
        return shorttext1567761455594;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761455594
     *
     * @param shorttext1567761455594 the value for igtgv_pjldc01dcb.ShortText1567761455594
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761455594(String shorttext1567761455594) {
        this.shorttext1567761455594 = shorttext1567761455594 == null ? null : shorttext1567761455594.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761846314
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761846314
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761846314() {
        return shorttext1567761846314;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761846314
     *
     * @param shorttext1567761846314 the value for igtgv_pjldc01dcb.ShortText1567761846314
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761846314(String shorttext1567761846314) {
        this.shorttext1567761846314 = shorttext1567761846314 == null ? null : shorttext1567761846314.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761886218
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761886218
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761886218() {
        return shorttext1567761886218;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761886218
     *
     * @param shorttext1567761886218 the value for igtgv_pjldc01dcb.ShortText1567761886218
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761886218(String shorttext1567761886218) {
        this.shorttext1567761886218 = shorttext1567761886218 == null ? null : shorttext1567761886218.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761904178
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761904178
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761904178() {
        return shorttext1567761904178;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761904178
     *
     * @param shorttext1567761904178 the value for igtgv_pjldc01dcb.ShortText1567761904178
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761904178(String shorttext1567761904178) {
        this.shorttext1567761904178 = shorttext1567761904178 == null ? null : shorttext1567761904178.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567761983306
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567761983306
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567761983306() {
        return shorttext1567761983306;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567761983306
     *
     * @param shorttext1567761983306 the value for igtgv_pjldc01dcb.ShortText1567761983306
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567761983306(String shorttext1567761983306) {
        this.shorttext1567761983306 = shorttext1567761983306 == null ? null : shorttext1567761983306.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762030586
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762030586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762030586() {
        return shorttext1567762030586;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762030586
     *
     * @param shorttext1567762030586 the value for igtgv_pjldc01dcb.ShortText1567762030586
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762030586(String shorttext1567762030586) {
        this.shorttext1567762030586 = shorttext1567762030586 == null ? null : shorttext1567762030586.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762120642
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762120642
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762120642() {
        return shorttext1567762120642;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762120642
     *
     * @param shorttext1567762120642 the value for igtgv_pjldc01dcb.ShortText1567762120642
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762120642(String shorttext1567762120642) {
        this.shorttext1567762120642 = shorttext1567762120642 == null ? null : shorttext1567762120642.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762172409
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762172409
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762172409() {
        return shorttext1567762172409;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762172409
     *
     * @param shorttext1567762172409 the value for igtgv_pjldc01dcb.ShortText1567762172409
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762172409(String shorttext1567762172409) {
        this.shorttext1567762172409 = shorttext1567762172409 == null ? null : shorttext1567762172409.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762180513
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762180513
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762180513() {
        return shorttext1567762180513;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762180513
     *
     * @param shorttext1567762180513 the value for igtgv_pjldc01dcb.ShortText1567762180513
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762180513(String shorttext1567762180513) {
        this.shorttext1567762180513 = shorttext1567762180513 == null ? null : shorttext1567762180513.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762191345
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762191345
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762191345() {
        return shorttext1567762191345;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762191345
     *
     * @param shorttext1567762191345 the value for igtgv_pjldc01dcb.ShortText1567762191345
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762191345(String shorttext1567762191345) {
        this.shorttext1567762191345 = shorttext1567762191345 == null ? null : shorttext1567762191345.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762656480
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762656480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762656480() {
        return shorttext1567762656480;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762656480
     *
     * @param shorttext1567762656480 the value for igtgv_pjldc01dcb.ShortText1567762656480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762656480(String shorttext1567762656480) {
        this.shorttext1567762656480 = shorttext1567762656480 == null ? null : shorttext1567762656480.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762796954
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762796954
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762796954() {
        return shorttext1567762796954;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762796954
     *
     * @param shorttext1567762796954 the value for igtgv_pjldc01dcb.ShortText1567762796954
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762796954(String shorttext1567762796954) {
        this.shorttext1567762796954 = shorttext1567762796954 == null ? null : shorttext1567762796954.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567762822969
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567762822969
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567762822969() {
        return shorttext1567762822969;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567762822969
     *
     * @param shorttext1567762822969 the value for igtgv_pjldc01dcb.ShortText1567762822969
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567762822969(String shorttext1567762822969) {
        this.shorttext1567762822969 = shorttext1567762822969 == null ? null : shorttext1567762822969.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567995553359
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567995553359
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567995553359() {
        return shorttext1567995553359;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567995553359
     *
     * @param shorttext1567995553359 the value for igtgv_pjldc01dcb.ShortText1567995553359
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567995553359(String shorttext1567995553359) {
        this.shorttext1567995553359 = shorttext1567995553359 == null ? null : shorttext1567995553359.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1567995610591
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1567995610591
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1567995610591() {
        return shorttext1567995610591;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1567995610591
     *
     * @param shorttext1567995610591 the value for igtgv_pjldc01dcb.ShortText1567995610591
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1567995610591(String shorttext1567995610591) {
        this.shorttext1567995610591 = shorttext1567995610591 == null ? null : shorttext1567995610591.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1568085486500
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1568085486500
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1568085486500() {
        return shorttext1568085486500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1568085486500
     *
     * @param shorttext1568085486500 the value for igtgv_pjldc01dcb.ShortText1568085486500
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1568085486500(String shorttext1568085486500) {
        this.shorttext1568085486500 = shorttext1568085486500 == null ? null : shorttext1568085486500.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1568085736789
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1568085736789
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1568085736789() {
        return shorttext1568085736789;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1568085736789
     *
     * @param shorttext1568085736789 the value for igtgv_pjldc01dcb.ShortText1568085736789
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1568085736789(String shorttext1568085736789) {
        this.shorttext1568085736789 = shorttext1568085736789 == null ? null : shorttext1568085736789.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1568259391751
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1568259391751
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1568259391751() {
        return shorttext1568259391751;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1568259391751
     *
     * @param shorttext1568259391751 the value for igtgv_pjldc01dcb.ShortText1568259391751
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1568259391751(String shorttext1568259391751) {
        this.shorttext1568259391751 = shorttext1568259391751 == null ? null : shorttext1568259391751.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728158252
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728158252
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728158252() {
        return shorttext1569728158252;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728158252
     *
     * @param shorttext1569728158252 the value for igtgv_pjldc01dcb.ShortText1569728158252
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728158252(String shorttext1569728158252) {
        this.shorttext1569728158252 = shorttext1569728158252 == null ? null : shorttext1569728158252.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728170780
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728170780
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728170780() {
        return shorttext1569728170780;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728170780
     *
     * @param shorttext1569728170780 the value for igtgv_pjldc01dcb.ShortText1569728170780
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728170780(String shorttext1569728170780) {
        this.shorttext1569728170780 = shorttext1569728170780 == null ? null : shorttext1569728170780.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728174540
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728174540
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728174540() {
        return shorttext1569728174540;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728174540
     *
     * @param shorttext1569728174540 the value for igtgv_pjldc01dcb.ShortText1569728174540
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728174540(String shorttext1569728174540) {
        this.shorttext1569728174540 = shorttext1569728174540 == null ? null : shorttext1569728174540.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728177604
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728177604
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728177604() {
        return shorttext1569728177604;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728177604
     *
     * @param shorttext1569728177604 the value for igtgv_pjldc01dcb.ShortText1569728177604
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728177604(String shorttext1569728177604) {
        this.shorttext1569728177604 = shorttext1569728177604 == null ? null : shorttext1569728177604.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728336907
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728336907
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728336907() {
        return shorttext1569728336907;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728336907
     *
     * @param shorttext1569728336907 the value for igtgv_pjldc01dcb.ShortText1569728336907
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728336907(String shorttext1569728336907) {
        this.shorttext1569728336907 = shorttext1569728336907 == null ? null : shorttext1569728336907.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728465060
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728465060
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728465060() {
        return shorttext1569728465060;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728465060
     *
     * @param shorttext1569728465060 the value for igtgv_pjldc01dcb.ShortText1569728465060
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728465060(String shorttext1569728465060) {
        this.shorttext1569728465060 = shorttext1569728465060 == null ? null : shorttext1569728465060.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569728948491
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569728948491
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569728948491() {
        return shorttext1569728948491;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569728948491
     *
     * @param shorttext1569728948491 the value for igtgv_pjldc01dcb.ShortText1569728948491
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569728948491(String shorttext1569728948491) {
        this.shorttext1569728948491 = shorttext1569728948491 == null ? null : shorttext1569728948491.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569729016795
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569729016795
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569729016795() {
        return shorttext1569729016795;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569729016795
     *
     * @param shorttext1569729016795 the value for igtgv_pjldc01dcb.ShortText1569729016795
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569729016795(String shorttext1569729016795) {
        this.shorttext1569729016795 = shorttext1569729016795 == null ? null : shorttext1569729016795.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569738095498
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569738095498
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569738095498() {
        return shorttext1569738095498;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569738095498
     *
     * @param shorttext1569738095498 the value for igtgv_pjldc01dcb.ShortText1569738095498
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569738095498(String shorttext1569738095498) {
        this.shorttext1569738095498 = shorttext1569738095498 == null ? null : shorttext1569738095498.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569738368009
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569738368009
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569738368009() {
        return shorttext1569738368009;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569738368009
     *
     * @param shorttext1569738368009 the value for igtgv_pjldc01dcb.ShortText1569738368009
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569738368009(String shorttext1569738368009) {
        this.shorttext1569738368009 = shorttext1569738368009 == null ? null : shorttext1569738368009.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569738587480
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569738587480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569738587480() {
        return shorttext1569738587480;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569738587480
     *
     * @param shorttext1569738587480 the value for igtgv_pjldc01dcb.ShortText1569738587480
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569738587480(String shorttext1569738587480) {
        this.shorttext1569738587480 = shorttext1569738587480 == null ? null : shorttext1569738587480.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569738939775
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569738939775
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569738939775() {
        return shorttext1569738939775;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569738939775
     *
     * @param shorttext1569738939775 the value for igtgv_pjldc01dcb.ShortText1569738939775
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569738939775(String shorttext1569738939775) {
        this.shorttext1569738939775 = shorttext1569738939775 == null ? null : shorttext1569738939775.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1569742452564
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1569742452564
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1569742452564() {
        return shorttext1569742452564;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1569742452564
     *
     * @param shorttext1569742452564 the value for igtgv_pjldc01dcb.ShortText1569742452564
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1569742452564(String shorttext1569742452564) {
        this.shorttext1569742452564 = shorttext1569742452564 == null ? null : shorttext1569742452564.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1570524392514
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1570524392514
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1570524392514() {
        return shorttext1570524392514;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1570524392514
     *
     * @param shorttext1570524392514 the value for igtgv_pjldc01dcb.ShortText1570524392514
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1570524392514(String shorttext1570524392514) {
        this.shorttext1570524392514 = shorttext1570524392514 == null ? null : shorttext1570524392514.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1571127984437
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1571127984437
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1571127984437() {
        return shorttext1571127984437;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1571127984437
     *
     * @param shorttext1571127984437 the value for igtgv_pjldc01dcb.ShortText1571127984437
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1571127984437(String shorttext1571127984437) {
        this.shorttext1571127984437 = shorttext1571127984437 == null ? null : shorttext1571127984437.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572406658886
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572406658886
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572406658886() {
        return shorttext1572406658886;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572406658886
     *
     * @param shorttext1572406658886 the value for igtgv_pjldc01dcb.ShortText1572406658886
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572406658886(String shorttext1572406658886) {
        this.shorttext1572406658886 = shorttext1572406658886 == null ? null : shorttext1572406658886.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572406711365
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572406711365
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572406711365() {
        return shorttext1572406711365;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572406711365
     *
     * @param shorttext1572406711365 the value for igtgv_pjldc01dcb.ShortText1572406711365
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572406711365(String shorttext1572406711365) {
        this.shorttext1572406711365 = shorttext1572406711365 == null ? null : shorttext1572406711365.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572406751109
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572406751109
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572406751109() {
        return shorttext1572406751109;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572406751109
     *
     * @param shorttext1572406751109 the value for igtgv_pjldc01dcb.ShortText1572406751109
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572406751109(String shorttext1572406751109) {
        this.shorttext1572406751109 = shorttext1572406751109 == null ? null : shorttext1572406751109.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.RelevanceForm1572412237878
     *
     * @return the value of igtgv_pjldc01dcb.RelevanceForm1572412237878
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getRelevanceform1572412237878() {
        return relevanceform1572412237878;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.RelevanceForm1572412237878
     *
     * @param relevanceform1572412237878 the value for igtgv_pjldc01dcb.RelevanceForm1572412237878
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setRelevanceform1572412237878(String relevanceform1572412237878) {
        this.relevanceform1572412237878 = relevanceform1572412237878 == null ? null : relevanceform1572412237878.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425570081
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425570081
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425570081() {
        return shorttext1572425570081;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425570081
     *
     * @param shorttext1572425570081 the value for igtgv_pjldc01dcb.ShortText1572425570081
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425570081(String shorttext1572425570081) {
        this.shorttext1572425570081 = shorttext1572425570081 == null ? null : shorttext1572425570081.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425616210
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425616210
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425616210() {
        return shorttext1572425616210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425616210
     *
     * @param shorttext1572425616210 the value for igtgv_pjldc01dcb.ShortText1572425616210
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425616210(String shorttext1572425616210) {
        this.shorttext1572425616210 = shorttext1572425616210 == null ? null : shorttext1572425616210.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425629179
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425629179
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425629179() {
        return shorttext1572425629179;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425629179
     *
     * @param shorttext1572425629179 the value for igtgv_pjldc01dcb.ShortText1572425629179
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425629179(String shorttext1572425629179) {
        this.shorttext1572425629179 = shorttext1572425629179 == null ? null : shorttext1572425629179.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425638936
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425638936
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425638936() {
        return shorttext1572425638936;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425638936
     *
     * @param shorttext1572425638936 the value for igtgv_pjldc01dcb.ShortText1572425638936
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425638936(String shorttext1572425638936) {
        this.shorttext1572425638936 = shorttext1572425638936 == null ? null : shorttext1572425638936.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425645745
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425645745
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425645745() {
        return shorttext1572425645745;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425645745
     *
     * @param shorttext1572425645745 the value for igtgv_pjldc01dcb.ShortText1572425645745
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425645745(String shorttext1572425645745) {
        this.shorttext1572425645745 = shorttext1572425645745 == null ? null : shorttext1572425645745.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425675200
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425675200
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425675200() {
        return shorttext1572425675200;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425675200
     *
     * @param shorttext1572425675200 the value for igtgv_pjldc01dcb.ShortText1572425675200
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425675200(String shorttext1572425675200) {
        this.shorttext1572425675200 = shorttext1572425675200 == null ? null : shorttext1572425675200.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1572425697073
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1572425697073
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1572425697073() {
        return shorttext1572425697073;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1572425697073
     *
     * @param shorttext1572425697073 the value for igtgv_pjldc01dcb.ShortText1572425697073
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1572425697073(String shorttext1572425697073) {
        this.shorttext1572425697073 = shorttext1572425697073 == null ? null : shorttext1572425697073.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1578362642317
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1578362642317
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1578362642317() {
        return shorttext1578362642317;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1578362642317
     *
     * @param shorttext1578362642317 the value for igtgv_pjldc01dcb.ShortText1578362642317
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1578362642317(String shorttext1578362642317) {
        this.shorttext1578362642317 = shorttext1578362642317 == null ? null : shorttext1578362642317.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1578464014747
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1578464014747
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1578464014747() {
        return shorttext1578464014747;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1578464014747
     *
     * @param shorttext1578464014747 the value for igtgv_pjldc01dcb.ShortText1578464014747
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1578464014747(String shorttext1578464014747) {
        this.shorttext1578464014747 = shorttext1578464014747 == null ? null : shorttext1578464014747.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1578472359364
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1578472359364
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1578472359364() {
        return shorttext1578472359364;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1578472359364
     *
     * @param shorttext1578472359364 the value for igtgv_pjldc01dcb.ShortText1578472359364
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1578472359364(String shorttext1578472359364) {
        this.shorttext1578472359364 = shorttext1578472359364 == null ? null : shorttext1578472359364.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1583372194313
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1583372194313
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1583372194313() {
        return shorttext1583372194313;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1583372194313
     *
     * @param shorttext1583372194313 the value for igtgv_pjldc01dcb.ShortText1583372194313
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1583372194313(String shorttext1583372194313) {
        this.shorttext1583372194313 = shorttext1583372194313 == null ? null : shorttext1583372194313.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1584003163176
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1584003163176
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1584003163176() {
        return shorttext1584003163176;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1584003163176
     *
     * @param shorttext1584003163176 the value for igtgv_pjldc01dcb.ShortText1584003163176
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1584003163176(String shorttext1584003163176) {
        this.shorttext1584003163176 = shorttext1584003163176 == null ? null : shorttext1584003163176.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.ShortText1584003915711
     *
     * @return the value of igtgv_pjldc01dcb.ShortText1584003915711
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getShorttext1584003915711() {
        return shorttext1584003915711;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.ShortText1584003915711
     *
     * @param shorttext1584003915711 the value for igtgv_pjldc01dcb.ShortText1584003915711
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setShorttext1584003915711(String shorttext1584003915711) {
        this.shorttext1584003915711 = shorttext1584003915711 == null ? null : shorttext1584003915711.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.city
     *
     * @return the value of igtgv_pjldc01dcb.city
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.city
     *
     * @param city the value for igtgv_pjldc01dcb.city
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.country
     *
     * @return the value of igtgv_pjldc01dcb.country
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.country
     *
     * @param country the value for igtgv_pjldc01dcb.country
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.value
     *
     * @return the value of igtgv_pjldc01dcb.value
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.value
     *
     * @param value the value for igtgv_pjldc01dcb.value
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}