package com.guizhou.map.domain;

import java.io.Serializable;
import java.util.Date;

public class fungus  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.id
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.parent_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String parentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.collec_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private Date collecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.gatherer
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String gatherer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.province
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.city
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.county
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.town
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String town;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.village
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String village;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.in_protection
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String inProtection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.longitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.latitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.height
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.weather
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String weather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.species_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String speciesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.latin_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String latinName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.kingdom
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String kingdom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.phylum
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String phylum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.gClass
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String gclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.order1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String order1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.family1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String family1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.genus1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String genus1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.specimen_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String specimenNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.live_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String liveNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.strain_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String strainNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.material1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String material1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.fungus_type1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String fungusType1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.ecosystem
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String ecosystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.related_vegetation
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String relatedVegetation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.location
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.aspect
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String aspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.eco_condition
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String ecoCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.substrate
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String substrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.interference
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String interference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.habit
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String habit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.nutrition_type
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String nutritionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.feature
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.collect_site
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String collectSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.preserve_mode
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String preserveMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.threat_factor
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String threatFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.economic_value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String economicValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.endangered_degree
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String endangeredDegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.is_special
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String isSpecial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.new_record_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String newRecordSpecies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.new_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String newSpecies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.sample_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String sampleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.experiment_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String experimentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.sequence_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String sequenceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungus_data.img
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.id
     *
     * @return the value of fungus_data.id
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.id
     *
     * @param id the value for fungus_data.id
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.no
     *
     * @return the value of fungus_data.no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.no
     *
     * @param no the value for fungus_data.no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.parent_no
     *
     * @return the value of fungus_data.parent_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getParentNo() {
        return parentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.parent_no
     *
     * @param parentNo the value for fungus_data.parent_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setParentNo(String parentNo) {
        this.parentNo = parentNo == null ? null : parentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.collec_time
     *
     * @return the value of fungus_data.collec_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public Date getCollecTime() {
        return collecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.collec_time
     *
     * @param collecTime the value for fungus_data.collec_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setCollecTime(Date collecTime) {
        this.collecTime = collecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.gatherer
     *
     * @return the value of fungus_data.gatherer
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getGatherer() {
        return gatherer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.gatherer
     *
     * @param gatherer the value for fungus_data.gatherer
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setGatherer(String gatherer) {
        this.gatherer = gatherer == null ? null : gatherer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.province
     *
     * @return the value of fungus_data.province
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.province
     *
     * @param province the value for fungus_data.province
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.city
     *
     * @return the value of fungus_data.city
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.city
     *
     * @param city the value for fungus_data.city
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.county
     *
     * @return the value of fungus_data.county
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.county
     *
     * @param county the value for fungus_data.county
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.town
     *
     * @return the value of fungus_data.town
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.town
     *
     * @param town the value for fungus_data.town
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.village
     *
     * @return the value of fungus_data.village
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.village
     *
     * @param village the value for fungus_data.village
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setVillage(String village) {
        this.village = village == null ? null : village.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.in_protection
     *
     * @return the value of fungus_data.in_protection
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getInProtection() {
        return inProtection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.in_protection
     *
     * @param inProtection the value for fungus_data.in_protection
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setInProtection(String inProtection) {
        this.inProtection = inProtection == null ? null : inProtection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.longitude
     *
     * @return the value of fungus_data.longitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.longitude
     *
     * @param longitude the value for fungus_data.longitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.latitude
     *
     * @return the value of fungus_data.latitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.latitude
     *
     * @param latitude the value for fungus_data.latitude
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.height
     *
     * @return the value of fungus_data.height
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.height
     *
     * @param height the value for fungus_data.height
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.weather
     *
     * @return the value of fungus_data.weather
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.weather
     *
     * @param weather the value for fungus_data.weather
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.species_name
     *
     * @return the value of fungus_data.species_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.species_name
     *
     * @param speciesName the value for fungus_data.species_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName == null ? null : speciesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.latin_name
     *
     * @return the value of fungus_data.latin_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getLatinName() {
        return latinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.latin_name
     *
     * @param latinName the value for fungus_data.latin_name
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setLatinName(String latinName) {
        this.latinName = latinName == null ? null : latinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.kingdom
     *
     * @return the value of fungus_data.kingdom
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getKingdom() {
        return kingdom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.kingdom
     *
     * @param kingdom the value for fungus_data.kingdom
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setKingdom(String kingdom) {
        this.kingdom = kingdom == null ? null : kingdom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.phylum
     *
     * @return the value of fungus_data.phylum
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getPhylum() {
        return phylum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.phylum
     *
     * @param phylum the value for fungus_data.phylum
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setPhylum(String phylum) {
        this.phylum = phylum == null ? null : phylum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.gClass
     *
     * @return the value of fungus_data.gClass
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getGclass() {
        return gclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.gClass
     *
     * @param gclass the value for fungus_data.gClass
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setGclass(String gclass) {
        this.gclass = gclass == null ? null : gclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.order1
     *
     * @return the value of fungus_data.order1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getOrder1() {
        return order1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.order1
     *
     * @param order1 the value for fungus_data.order1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setOrder1(String order1) {
        this.order1 = order1 == null ? null : order1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.family1
     *
     * @return the value of fungus_data.family1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getFamily1() {
        return family1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.family1
     *
     * @param family1 the value for fungus_data.family1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setFamily1(String family1) {
        this.family1 = family1 == null ? null : family1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.genus1
     *
     * @return the value of fungus_data.genus1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getGenus1() {
        return genus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.genus1
     *
     * @param genus1 the value for fungus_data.genus1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setGenus1(String genus1) {
        this.genus1 = genus1 == null ? null : genus1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.specimen_no1
     *
     * @return the value of fungus_data.specimen_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getSpecimenNo1() {
        return specimenNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.specimen_no1
     *
     * @param specimenNo1 the value for fungus_data.specimen_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setSpecimenNo1(String specimenNo1) {
        this.specimenNo1 = specimenNo1 == null ? null : specimenNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.live_no1
     *
     * @return the value of fungus_data.live_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getLiveNo1() {
        return liveNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.live_no1
     *
     * @param liveNo1 the value for fungus_data.live_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setLiveNo1(String liveNo1) {
        this.liveNo1 = liveNo1 == null ? null : liveNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.strain_no1
     *
     * @return the value of fungus_data.strain_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getStrainNo1() {
        return strainNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.strain_no1
     *
     * @param strainNo1 the value for fungus_data.strain_no1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setStrainNo1(String strainNo1) {
        this.strainNo1 = strainNo1 == null ? null : strainNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.material1
     *
     * @return the value of fungus_data.material1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getMaterial1() {
        return material1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.material1
     *
     * @param material1 the value for fungus_data.material1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setMaterial1(String material1) {
        this.material1 = material1 == null ? null : material1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.fungus_type1
     *
     * @return the value of fungus_data.fungus_type1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getFungusType1() {
        return fungusType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.fungus_type1
     *
     * @param fungusType1 the value for fungus_data.fungus_type1
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setFungusType1(String fungusType1) {
        this.fungusType1 = fungusType1 == null ? null : fungusType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.ecosystem
     *
     * @return the value of fungus_data.ecosystem
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getEcosystem() {
        return ecosystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.ecosystem
     *
     * @param ecosystem the value for fungus_data.ecosystem
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setEcosystem(String ecosystem) {
        this.ecosystem = ecosystem == null ? null : ecosystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.related_vegetation
     *
     * @return the value of fungus_data.related_vegetation
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getRelatedVegetation() {
        return relatedVegetation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.related_vegetation
     *
     * @param relatedVegetation the value for fungus_data.related_vegetation
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setRelatedVegetation(String relatedVegetation) {
        this.relatedVegetation = relatedVegetation == null ? null : relatedVegetation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.location
     *
     * @return the value of fungus_data.location
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.location
     *
     * @param location the value for fungus_data.location
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.aspect
     *
     * @return the value of fungus_data.aspect
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getAspect() {
        return aspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.aspect
     *
     * @param aspect the value for fungus_data.aspect
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setAspect(String aspect) {
        this.aspect = aspect == null ? null : aspect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.eco_condition
     *
     * @return the value of fungus_data.eco_condition
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getEcoCondition() {
        return ecoCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.eco_condition
     *
     * @param ecoCondition the value for fungus_data.eco_condition
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setEcoCondition(String ecoCondition) {
        this.ecoCondition = ecoCondition == null ? null : ecoCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.substrate
     *
     * @return the value of fungus_data.substrate
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getSubstrate() {
        return substrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.substrate
     *
     * @param substrate the value for fungus_data.substrate
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setSubstrate(String substrate) {
        this.substrate = substrate == null ? null : substrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.interference
     *
     * @return the value of fungus_data.interference
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getInterference() {
        return interference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.interference
     *
     * @param interference the value for fungus_data.interference
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setInterference(String interference) {
        this.interference = interference == null ? null : interference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.habit
     *
     * @return the value of fungus_data.habit
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getHabit() {
        return habit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.habit
     *
     * @param habit the value for fungus_data.habit
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setHabit(String habit) {
        this.habit = habit == null ? null : habit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.nutrition_type
     *
     * @return the value of fungus_data.nutrition_type
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getNutritionType() {
        return nutritionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.nutrition_type
     *
     * @param nutritionType the value for fungus_data.nutrition_type
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setNutritionType(String nutritionType) {
        this.nutritionType = nutritionType == null ? null : nutritionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.feature
     *
     * @return the value of fungus_data.feature
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.feature
     *
     * @param feature the value for fungus_data.feature
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.collect_site
     *
     * @return the value of fungus_data.collect_site
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getCollectSite() {
        return collectSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.collect_site
     *
     * @param collectSite the value for fungus_data.collect_site
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setCollectSite(String collectSite) {
        this.collectSite = collectSite == null ? null : collectSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.preserve_mode
     *
     * @return the value of fungus_data.preserve_mode
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getPreserveMode() {
        return preserveMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.preserve_mode
     *
     * @param preserveMode the value for fungus_data.preserve_mode
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setPreserveMode(String preserveMode) {
        this.preserveMode = preserveMode == null ? null : preserveMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.threat_factor
     *
     * @return the value of fungus_data.threat_factor
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getThreatFactor() {
        return threatFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.threat_factor
     *
     * @param threatFactor the value for fungus_data.threat_factor
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setThreatFactor(String threatFactor) {
        this.threatFactor = threatFactor == null ? null : threatFactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.economic_value
     *
     * @return the value of fungus_data.economic_value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getEconomicValue() {
        return economicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.economic_value
     *
     * @param economicValue the value for fungus_data.economic_value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setEconomicValue(String economicValue) {
        this.economicValue = economicValue == null ? null : economicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.endangered_degree
     *
     * @return the value of fungus_data.endangered_degree
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getEndangeredDegree() {
        return endangeredDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.endangered_degree
     *
     * @param endangeredDegree the value for fungus_data.endangered_degree
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setEndangeredDegree(String endangeredDegree) {
        this.endangeredDegree = endangeredDegree == null ? null : endangeredDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.is_special
     *
     * @return the value of fungus_data.is_special
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.is_special
     *
     * @param isSpecial the value for fungus_data.is_special
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setIsSpecial(String isSpecial) {
        this.isSpecial = isSpecial == null ? null : isSpecial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.new_record_species
     *
     * @return the value of fungus_data.new_record_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getNewRecordSpecies() {
        return newRecordSpecies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.new_record_species
     *
     * @param newRecordSpecies the value for fungus_data.new_record_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setNewRecordSpecies(String newRecordSpecies) {
        this.newRecordSpecies = newRecordSpecies == null ? null : newRecordSpecies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.new_species
     *
     * @return the value of fungus_data.new_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getNewSpecies() {
        return newSpecies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.new_species
     *
     * @param newSpecies the value for fungus_data.new_species
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setNewSpecies(String newSpecies) {
        this.newSpecies = newSpecies == null ? null : newSpecies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.sample_no
     *
     * @return the value of fungus_data.sample_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getSampleNo() {
        return sampleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.sample_no
     *
     * @param sampleNo the value for fungus_data.sample_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setSampleNo(String sampleNo) {
        this.sampleNo = sampleNo == null ? null : sampleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.experiment_no
     *
     * @return the value of fungus_data.experiment_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getExperimentNo() {
        return experimentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.experiment_no
     *
     * @param experimentNo the value for fungus_data.experiment_no
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setExperimentNo(String experimentNo) {
        this.experimentNo = experimentNo == null ? null : experimentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.sequence_time
     *
     * @return the value of fungus_data.sequence_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getSequenceTime() {
        return sequenceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.sequence_time
     *
     * @param sequenceTime the value for fungus_data.sequence_time
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setSequenceTime(String sequenceTime) {
        this.sequenceTime = sequenceTime == null ? null : sequenceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.value
     *
     * @return the value of fungus_data.value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.value
     *
     * @param value the value for fungus_data.value
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungus_data.img
     *
     * @return the value of fungus_data.img
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungus_data.img
     *
     * @param img the value for fungus_data.img
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}