package com.guizhou.map.domain;

public class Fungi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungi.id
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungi.name
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungi.latitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungi.longitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fungi.value
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungi.id
     *
     * @return the value of fungi.id
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungi.id
     *
     * @param id the value for fungi.id
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungi.name
     *
     * @return the value of fungi.name
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungi.name
     *
     * @param name the value for fungi.name
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungi.latitude
     *
     * @return the value of fungi.latitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungi.latitude
     *
     * @param latitude the value for fungi.latitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungi.longitude
     *
     * @return the value of fungi.longitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungi.longitude
     *
     * @param longitude the value for fungi.longitude
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fungi.value
     *
     * @return the value of fungi.value
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fungi.value
     *
     * @param value the value for fungi.value
     *
     * @mbg.generated Thu Aug 13 14:30:54 CST 2020
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}