package com.guizhou.map.domain;

public class fungusWithBLOBs extends fungus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.StaffSelector1567760753916
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String staffselector1567760753916;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column igtgv_pjldc01dcb.LongText1567762200825
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    private String longtext1567762200825;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.StaffSelector1567760753916
     *
     * @return the value of igtgv_pjldc01dcb.StaffSelector1567760753916
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getStaffselector1567760753916() {
        return staffselector1567760753916;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.StaffSelector1567760753916
     *
     * @param staffselector1567760753916 the value for igtgv_pjldc01dcb.StaffSelector1567760753916
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setStaffselector1567760753916(String staffselector1567760753916) {
        this.staffselector1567760753916 = staffselector1567760753916 == null ? null : staffselector1567760753916.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column igtgv_pjldc01dcb.LongText1567762200825
     *
     * @return the value of igtgv_pjldc01dcb.LongText1567762200825
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public String getLongtext1567762200825() {
        return longtext1567762200825;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column igtgv_pjldc01dcb.LongText1567762200825
     *
     * @param longtext1567762200825 the value for igtgv_pjldc01dcb.LongText1567762200825
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    public void setLongtext1567762200825(String longtext1567762200825) {
        this.longtext1567762200825 = longtext1567762200825 == null ? null : longtext1567762200825.trim();
    }
}