package com.guizhou.map.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class idtoimgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public idtoimgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBizobjectidIsNull() {
            addCriterion("bizObjectId is null");
            return (Criteria) this;
        }

        public Criteria andBizobjectidIsNotNull() {
            addCriterion("bizObjectId is not null");
            return (Criteria) this;
        }

        public Criteria andBizobjectidEqualTo(String value) {
            addCriterion("bizObjectId =", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidNotEqualTo(String value) {
            addCriterion("bizObjectId <>", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidGreaterThan(String value) {
            addCriterion("bizObjectId >", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidGreaterThanOrEqualTo(String value) {
            addCriterion("bizObjectId >=", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidLessThan(String value) {
            addCriterion("bizObjectId <", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidLessThanOrEqualTo(String value) {
            addCriterion("bizObjectId <=", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidLike(String value) {
            addCriterion("bizObjectId like", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidNotLike(String value) {
            addCriterion("bizObjectId not like", value, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidIn(List<String> values) {
            addCriterion("bizObjectId in", values, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidNotIn(List<String> values) {
            addCriterion("bizObjectId not in", values, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidBetween(String value1, String value2) {
            addCriterion("bizObjectId between", value1, value2, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizobjectidNotBetween(String value1, String value2) {
            addCriterion("bizObjectId not between", value1, value2, "bizobjectid");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeIsNull() {
            addCriterion("bizPropertyCode is null");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeIsNotNull() {
            addCriterion("bizPropertyCode is not null");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeEqualTo(String value) {
            addCriterion("bizPropertyCode =", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeNotEqualTo(String value) {
            addCriterion("bizPropertyCode <>", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeGreaterThan(String value) {
            addCriterion("bizPropertyCode >", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeGreaterThanOrEqualTo(String value) {
            addCriterion("bizPropertyCode >=", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeLessThan(String value) {
            addCriterion("bizPropertyCode <", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeLessThanOrEqualTo(String value) {
            addCriterion("bizPropertyCode <=", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeLike(String value) {
            addCriterion("bizPropertyCode like", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeNotLike(String value) {
            addCriterion("bizPropertyCode not like", value, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeIn(List<String> values) {
            addCriterion("bizPropertyCode in", values, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeNotIn(List<String> values) {
            addCriterion("bizPropertyCode not in", values, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeBetween(String value1, String value2) {
            addCriterion("bizPropertyCode between", value1, value2, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andBizpropertycodeNotBetween(String value1, String value2) {
            addCriterion("bizPropertyCode not between", value1, value2, "bizpropertycode");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNull() {
            addCriterion("createdTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIsNotNull() {
            addCriterion("createdTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeEqualTo(Date value) {
            addCriterion("createdTime =", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotEqualTo(Date value) {
            addCriterion("createdTime <>", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThan(Date value) {
            addCriterion("createdTime >", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createdTime >=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThan(Date value) {
            addCriterion("createdTime <", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeLessThanOrEqualTo(Date value) {
            addCriterion("createdTime <=", value, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeIn(List<Date> values) {
            addCriterion("createdTime in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotIn(List<Date> values) {
            addCriterion("createdTime not in", values, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeBetween(Date value1, Date value2) {
            addCriterion("createdTime between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreatedtimeNotBetween(Date value1, Date value2) {
            addCriterion("createdTime not between", value1, value2, "createdtime");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andFileextensionIsNull() {
            addCriterion("fileExtension is null");
            return (Criteria) this;
        }

        public Criteria andFileextensionIsNotNull() {
            addCriterion("fileExtension is not null");
            return (Criteria) this;
        }

        public Criteria andFileextensionEqualTo(String value) {
            addCriterion("fileExtension =", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionNotEqualTo(String value) {
            addCriterion("fileExtension <>", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionGreaterThan(String value) {
            addCriterion("fileExtension >", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionGreaterThanOrEqualTo(String value) {
            addCriterion("fileExtension >=", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionLessThan(String value) {
            addCriterion("fileExtension <", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionLessThanOrEqualTo(String value) {
            addCriterion("fileExtension <=", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionLike(String value) {
            addCriterion("fileExtension like", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionNotLike(String value) {
            addCriterion("fileExtension not like", value, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionIn(List<String> values) {
            addCriterion("fileExtension in", values, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionNotIn(List<String> values) {
            addCriterion("fileExtension not in", values, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionBetween(String value1, String value2) {
            addCriterion("fileExtension between", value1, value2, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFileextensionNotBetween(String value1, String value2) {
            addCriterion("fileExtension not between", value1, value2, "fileextension");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNull() {
            addCriterion("fileSize is null");
            return (Criteria) this;
        }

        public Criteria andFilesizeIsNotNull() {
            addCriterion("fileSize is not null");
            return (Criteria) this;
        }

        public Criteria andFilesizeEqualTo(Integer value) {
            addCriterion("fileSize =", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotEqualTo(Integer value) {
            addCriterion("fileSize <>", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThan(Integer value) {
            addCriterion("fileSize >", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fileSize >=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThan(Integer value) {
            addCriterion("fileSize <", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeLessThanOrEqualTo(Integer value) {
            addCriterion("fileSize <=", value, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeIn(List<Integer> values) {
            addCriterion("fileSize in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotIn(List<Integer> values) {
            addCriterion("fileSize not in", values, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeBetween(Integer value1, Integer value2) {
            addCriterion("fileSize between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andFilesizeNotBetween(Integer value1, Integer value2) {
            addCriterion("fileSize not between", value1, value2, "filesize");
            return (Criteria) this;
        }

        public Criteria andMimetypeIsNull() {
            addCriterion("mimeType is null");
            return (Criteria) this;
        }

        public Criteria andMimetypeIsNotNull() {
            addCriterion("mimeType is not null");
            return (Criteria) this;
        }

        public Criteria andMimetypeEqualTo(String value) {
            addCriterion("mimeType =", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeNotEqualTo(String value) {
            addCriterion("mimeType <>", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeGreaterThan(String value) {
            addCriterion("mimeType >", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeGreaterThanOrEqualTo(String value) {
            addCriterion("mimeType >=", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeLessThan(String value) {
            addCriterion("mimeType <", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeLessThanOrEqualTo(String value) {
            addCriterion("mimeType <=", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeLike(String value) {
            addCriterion("mimeType like", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeNotLike(String value) {
            addCriterion("mimeType not like", value, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeIn(List<String> values) {
            addCriterion("mimeType in", values, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeNotIn(List<String> values) {
            addCriterion("mimeType not in", values, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeBetween(String value1, String value2) {
            addCriterion("mimeType between", value1, value2, "mimetype");
            return (Criteria) this;
        }

        public Criteria andMimetypeNotBetween(String value1, String value2) {
            addCriterion("mimeType not between", value1, value2, "mimetype");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidIsNull() {
            addCriterion("parentBizObjectId is null");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidIsNotNull() {
            addCriterion("parentBizObjectId is not null");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidEqualTo(String value) {
            addCriterion("parentBizObjectId =", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidNotEqualTo(String value) {
            addCriterion("parentBizObjectId <>", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidGreaterThan(String value) {
            addCriterion("parentBizObjectId >", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidGreaterThanOrEqualTo(String value) {
            addCriterion("parentBizObjectId >=", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidLessThan(String value) {
            addCriterion("parentBizObjectId <", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidLessThanOrEqualTo(String value) {
            addCriterion("parentBizObjectId <=", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidLike(String value) {
            addCriterion("parentBizObjectId like", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidNotLike(String value) {
            addCriterion("parentBizObjectId not like", value, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidIn(List<String> values) {
            addCriterion("parentBizObjectId in", values, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidNotIn(List<String> values) {
            addCriterion("parentBizObjectId not in", values, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidBetween(String value1, String value2) {
            addCriterion("parentBizObjectId between", value1, value2, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentbizobjectidNotBetween(String value1, String value2) {
            addCriterion("parentBizObjectId not between", value1, value2, "parentbizobjectid");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeIsNull() {
            addCriterion("parentSchemaCode is null");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeIsNotNull() {
            addCriterion("parentSchemaCode is not null");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeEqualTo(String value) {
            addCriterion("parentSchemaCode =", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeNotEqualTo(String value) {
            addCriterion("parentSchemaCode <>", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeGreaterThan(String value) {
            addCriterion("parentSchemaCode >", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeGreaterThanOrEqualTo(String value) {
            addCriterion("parentSchemaCode >=", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeLessThan(String value) {
            addCriterion("parentSchemaCode <", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeLessThanOrEqualTo(String value) {
            addCriterion("parentSchemaCode <=", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeLike(String value) {
            addCriterion("parentSchemaCode like", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeNotLike(String value) {
            addCriterion("parentSchemaCode not like", value, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeIn(List<String> values) {
            addCriterion("parentSchemaCode in", values, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeNotIn(List<String> values) {
            addCriterion("parentSchemaCode not in", values, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeBetween(String value1, String value2) {
            addCriterion("parentSchemaCode between", value1, value2, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andParentschemacodeNotBetween(String value1, String value2) {
            addCriterion("parentSchemaCode not between", value1, value2, "parentschemacode");
            return (Criteria) this;
        }

        public Criteria andRefidIsNull() {
            addCriterion("refId is null");
            return (Criteria) this;
        }

        public Criteria andRefidIsNotNull() {
            addCriterion("refId is not null");
            return (Criteria) this;
        }

        public Criteria andRefidEqualTo(String value) {
            addCriterion("refId =", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotEqualTo(String value) {
            addCriterion("refId <>", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidGreaterThan(String value) {
            addCriterion("refId >", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidGreaterThanOrEqualTo(String value) {
            addCriterion("refId >=", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidLessThan(String value) {
            addCriterion("refId <", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidLessThanOrEqualTo(String value) {
            addCriterion("refId <=", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidLike(String value) {
            addCriterion("refId like", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotLike(String value) {
            addCriterion("refId not like", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidIn(List<String> values) {
            addCriterion("refId in", values, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotIn(List<String> values) {
            addCriterion("refId not in", values, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidBetween(String value1, String value2) {
            addCriterion("refId between", value1, value2, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotBetween(String value1, String value2) {
            addCriterion("refId not between", value1, value2, "refid");
            return (Criteria) this;
        }

        public Criteria andSchemacodeIsNull() {
            addCriterion("schemaCode is null");
            return (Criteria) this;
        }

        public Criteria andSchemacodeIsNotNull() {
            addCriterion("schemaCode is not null");
            return (Criteria) this;
        }

        public Criteria andSchemacodeEqualTo(String value) {
            addCriterion("schemaCode =", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeNotEqualTo(String value) {
            addCriterion("schemaCode <>", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeGreaterThan(String value) {
            addCriterion("schemaCode >", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeGreaterThanOrEqualTo(String value) {
            addCriterion("schemaCode >=", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeLessThan(String value) {
            addCriterion("schemaCode <", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeLessThanOrEqualTo(String value) {
            addCriterion("schemaCode <=", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeLike(String value) {
            addCriterion("schemaCode like", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeNotLike(String value) {
            addCriterion("schemaCode not like", value, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeIn(List<String> values) {
            addCriterion("schemaCode in", values, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeNotIn(List<String> values) {
            addCriterion("schemaCode not in", values, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeBetween(String value1, String value2) {
            addCriterion("schemaCode between", value1, value2, "schemacode");
            return (Criteria) this;
        }

        public Criteria andSchemacodeNotBetween(String value1, String value2) {
            addCriterion("schemaCode not between", value1, value2, "schemacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_biz_attachment
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 18 16:59:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}