package com.guizhou.map.domain;

import java.util.Date;

public class idtoimg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.id
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.bizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String bizobjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.bizPropertyCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String bizpropertycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.createdTime
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private Date createdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.creater
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.fileExtension
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String fileextension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.fileSize
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private Integer filesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.mimeType
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String mimetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.name
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.parentBizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String parentbizobjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.parentSchemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String parentschemacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.refId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String refid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_biz_attachment.schemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    private String schemacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.id
     *
     * @return the value of h_biz_attachment.id
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.id
     *
     * @param id the value for h_biz_attachment.id
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.bizObjectId
     *
     * @return the value of h_biz_attachment.bizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getBizobjectid() {
        return bizobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.bizObjectId
     *
     * @param bizobjectid the value for h_biz_attachment.bizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setBizobjectid(String bizobjectid) {
        this.bizobjectid = bizobjectid == null ? null : bizobjectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.bizPropertyCode
     *
     * @return the value of h_biz_attachment.bizPropertyCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getBizpropertycode() {
        return bizpropertycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.bizPropertyCode
     *
     * @param bizpropertycode the value for h_biz_attachment.bizPropertyCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setBizpropertycode(String bizpropertycode) {
        this.bizpropertycode = bizpropertycode == null ? null : bizpropertycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.createdTime
     *
     * @return the value of h_biz_attachment.createdTime
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.createdTime
     *
     * @param createdtime the value for h_biz_attachment.createdTime
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.creater
     *
     * @return the value of h_biz_attachment.creater
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.creater
     *
     * @param creater the value for h_biz_attachment.creater
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.fileExtension
     *
     * @return the value of h_biz_attachment.fileExtension
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getFileextension() {
        return fileextension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.fileExtension
     *
     * @param fileextension the value for h_biz_attachment.fileExtension
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setFileextension(String fileextension) {
        this.fileextension = fileextension == null ? null : fileextension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.fileSize
     *
     * @return the value of h_biz_attachment.fileSize
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public Integer getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.fileSize
     *
     * @param filesize the value for h_biz_attachment.fileSize
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.mimeType
     *
     * @return the value of h_biz_attachment.mimeType
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getMimetype() {
        return mimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.mimeType
     *
     * @param mimetype the value for h_biz_attachment.mimeType
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype == null ? null : mimetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.name
     *
     * @return the value of h_biz_attachment.name
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.name
     *
     * @param name the value for h_biz_attachment.name
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.parentBizObjectId
     *
     * @return the value of h_biz_attachment.parentBizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getParentbizobjectid() {
        return parentbizobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.parentBizObjectId
     *
     * @param parentbizobjectid the value for h_biz_attachment.parentBizObjectId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setParentbizobjectid(String parentbizobjectid) {
        this.parentbizobjectid = parentbizobjectid == null ? null : parentbizobjectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.parentSchemaCode
     *
     * @return the value of h_biz_attachment.parentSchemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getParentschemacode() {
        return parentschemacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.parentSchemaCode
     *
     * @param parentschemacode the value for h_biz_attachment.parentSchemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setParentschemacode(String parentschemacode) {
        this.parentschemacode = parentschemacode == null ? null : parentschemacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.refId
     *
     * @return the value of h_biz_attachment.refId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getRefid() {
        return refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.refId
     *
     * @param refid the value for h_biz_attachment.refId
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setRefid(String refid) {
        this.refid = refid == null ? null : refid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_biz_attachment.schemaCode
     *
     * @return the value of h_biz_attachment.schemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public String getSchemacode() {
        return schemacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_biz_attachment.schemaCode
     *
     * @param schemacode the value for h_biz_attachment.schemaCode
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    public void setSchemacode(String schemacode) {
        this.schemacode = schemacode == null ? null : schemacode.trim();
    }
}