package com.guizhou.map.domain;

public class predict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.id
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.genus1
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String genus1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.longitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.latitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.value
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.city
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.country
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.probability
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String probability;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predict.specialname
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    private String specialname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.id
     *
     * @return the value of predict.id
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.id
     *
     * @param id the value for predict.id
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.genus1
     *
     * @return the value of predict.genus1
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getGenus1() {
        return genus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.genus1
     *
     * @param genus1 the value for predict.genus1
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setGenus1(String genus1) {
        this.genus1 = genus1 == null ? null : genus1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.longitude
     *
     * @return the value of predict.longitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.longitude
     *
     * @param longitude the value for predict.longitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.latitude
     *
     * @return the value of predict.latitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.latitude
     *
     * @param latitude the value for predict.latitude
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.value
     *
     * @return the value of predict.value
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.value
     *
     * @param value the value for predict.value
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.city
     *
     * @return the value of predict.city
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.city
     *
     * @param city the value for predict.city
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.country
     *
     * @return the value of predict.country
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.country
     *
     * @param country the value for predict.country
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.probability
     *
     * @return the value of predict.probability
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getProbability() {
        return probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.probability
     *
     * @param probability the value for predict.probability
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setProbability(String probability) {
        this.probability = probability == null ? null : probability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predict.specialname
     *
     * @return the value of predict.specialname
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public String getSpecialname() {
        return specialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predict.specialname
     *
     * @param specialname the value for predict.specialname
     *
     * @mbg.generated Tue Aug 04 09:15:36 CST 2020
     */
    public void setSpecialname(String specialname) {
        this.specialname = specialname == null ? null : specialname.trim();
    }
}