package com.guizhou.map.dao;

import com.guizhou.map.domain.coordinatetoimgid;
import com.guizhou.map.domain.coordinatetoimgidExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface coordinatetoimgidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    long countByExample(coordinatetoimgidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int deleteByExample(coordinatetoimgidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int insert(coordinatetoimgid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int insertSelective(coordinatetoimgid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    List<coordinatetoimgid> selectByExample(coordinatetoimgidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    coordinatetoimgid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") coordinatetoimgid record, @Param("example") coordinatetoimgidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int updateByExample(@Param("record") coordinatetoimgid record, @Param("example") coordinatetoimgidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int updateByPrimaryKeySelective(coordinatetoimgid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_longla
     *
     * @mbg.generated Tue Nov 19 09:48:23 CST 2019
     */
    int updateByPrimaryKey(coordinatetoimgid record);
}