package com.guizhou.map.dao;

import com.guizhou.map.domain.fungus;
import com.guizhou.map.domain.fungusExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface fungusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    long countByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int deleteByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int insert(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int insertSelective(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    List<fungus> selectByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    fungus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") fungus record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int updateByExample(@Param("record") fungus record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int updateByPrimaryKeySelective(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungus_data
     *
     * @mbg.generated Sat Nov 02 10:07:07 CST 2019
     */
    int updateByPrimaryKey(fungus record);
}