package com.guizhou.map.dao;

import com.guizhou.map.domain.fungus;
import com.guizhou.map.domain.fungusExample;
import com.guizhou.map.domain.fungusWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface fungusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    List<fungus> selectAll();
    List<fungus> selectByCity(String city);
    List<fungus> selectByCountry(String country);
    long countByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int deleteByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int insert(fungusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int insertSelective(fungusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    List<fungusWithBLOBs> selectByExampleWithBLOBs(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    List<fungus> selectByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    fungusWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") fungusWithBLOBs record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") fungusWithBLOBs record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByExample(@Param("record") fungus record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByPrimaryKeySelective(fungusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(fungusWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Mon Aug 03 15:23:16 CST 2020
     */
    int updateByPrimaryKey(fungus record);
}