package com.guizhou.map.dao;

import com.guizhou.map.domain.fungus;
import com.guizhou.map.domain.fungusExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface fungusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    List<fungus> selectAll();
    List<fungus> selectByCity(String city);
    List<fungus> selectByCountry(String country);
    long countByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int deleteByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int insert(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int insertSelective(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    List<fungus> selectByExample(fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    fungus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") fungus record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int updateByExample(@Param("record") fungus record, @Param("example") fungusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int updateByPrimaryKeySelective(fungus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table igtgv_pjldc01dcb
     *
     * @mbg.generated Thu Sep 24 10:26:55 CST 2020
     */
    int updateByPrimaryKey(fungus record);
}