package com.guizhou.map.dao;

import com.guizhou.map.domain.Fungi;
import com.guizhou.map.domain.FungiExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface FungiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    long countByExample(FungiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int deleteByExample(FungiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int insert(Fungi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int insertSelective(Fungi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    List<Fungi> selectByExample(FungiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    Fungi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fungi record, @Param("example") FungiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int updateByExample(@Param("record") Fungi record, @Param("example") FungiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int updateByPrimaryKeySelective(Fungi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fungi
     *
     * @mbg.generated Wed Aug 28 17:42:10 CST 2019
     */
    int updateByPrimaryKey(Fungi record);
}