package com.guizhou.map.dao;

import com.guizhou.map.domain.idtoimg;
import com.guizhou.map.domain.idtoimgExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface idtoimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    long countByExample(idtoimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int deleteByExample(idtoimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int insert(idtoimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int insertSelective(idtoimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    List<idtoimg> selectByExample(idtoimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    idtoimg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") idtoimg record, @Param("example") idtoimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int updateByExample(@Param("record") idtoimg record, @Param("example") idtoimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int updateByPrimaryKeySelective(idtoimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_biz_attachment
     *
     * @mbg.generated Mon Nov 18 16:59:31 CST 2019
     */
    int updateByPrimaryKey(idtoimg record);
}