package com.guizhou.map.dao;

import com.guizhou.map.domain.predict;
import com.guizhou.map.domain.predictExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface predictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    long countByExample(predictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int deleteByExample(predictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int insert(predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int insertSelective(predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    List<predict> selectByExample(predictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    predict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") predict record, @Param("example") predictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int updateByExample(@Param("record") predict record, @Param("example") predictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int updateByPrimaryKeySelective(predict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predict
     *
     * @mbg.generated Tue Nov 05 17:01:33 CST 2019
     */
    int updateByPrimaryKey(predict record);
}